repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev:  v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_docs_replace
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terrascan

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-yaml
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
